parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     gergelypolonkai
    database_user:     gergelypolonkai
    database_password: the8dooM

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            rie5chooqu8oche5ha6Keidop3ahxoob
