jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        GergelyPolonkai\FrontBundle\Entity\User:
            id: gergely_polonkai_front.service.crypt_encoder

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        gergely_polonkai_front.entity.user:
            entity:
                class: GergelyPolonkai\FrontBundle\Entity\User
                property: username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/admin/login.html$
            security: false

        secured_area:
            pattern:    ^/admin
            form_login:
                check_path: /admin/login-check.do
                login_path: /admin/login.html
            logout:
                path:   /admin/logout
                target: /
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
